import { EventInput } from "@fullcalendar/core";
import { AbstractControl, ValidatorFn } from "@angular/forms";
let eventGuid = 0;
const TODAY_STR = new Date().toISOString().replace(/T.*$/, ""); // YYYY-MM-DD of today

export const INITIAL_EVENTS: EventInput[] = [
  {
    id: createEventId(),
    title: "All-day event",
    start: TODAY_STR,
  },
  {
    id: createEventId(),
    title: "Timed event",
    start: TODAY_STR + "T00:00:00",
    // end: TODAY_STR + 'T03:00:00'
  },
  {
    id: createEventId(),
    title: "Timed event",
    start: TODAY_STR + "T12:00:00",
    // end: TODAY_STR + 'T15:00:00'
  },
];

export function noWhitespaceValidator(): ValidatorFn {
  return (control: AbstractControl): { [key: string]: any } | null => {
    const value: string = control.value;
    if (value && value.trim().length === 0) {
      return { whitespace: true };
    }
    return null;
  };
}
/*---------@function to constraint only letters in textfield------------*/
export function onlyLettersAllowed(event: any) {
  const pattern = /[a-zA-Z]/;  // Regular expression to allow only letters
  const inputChar = String.fromCharCode(event.charCode);

  if (!pattern.test(inputChar)) {
    event.preventDefault();  // Prevents the input character from being entered
  }
}
/*---------@function to constraint only numbers in textfield------------*/
export function onlyNumbersAllowed(event: any) {
  const pattern = /[0-9]/;  
  const inputChar = String.fromCharCode(event.charCode);

  if (!pattern.test(inputChar)) {
    event.preventDefault(); 
  }
}

/*---------@function to constraint only letters and space in textfield------------*/
export function onlyLettersAndSpaceAllowed(event: any) {
  const pattern = /[a-zA-Z]/;   
  const inputChar = String.fromCharCode(event.charCode);

  if (!pattern.test(inputChar)  && inputChar !== ' ') {
    event.preventDefault();  
  }
}
/*---------@function to constraint only alphanumeric and space in textfield------------*/
export function onlyAlphaNumericAllowed(event: any) {
  const pattern = /^[a-zA-Z0-9]+$/;  
  const inputChar = String.fromCharCode(event.charCode);

  if (!pattern.test(inputChar) && inputChar !== ' ') {
    event.preventDefault();  
  }
}


export function createEventId() {
  return String(eventGuid++);
}

export const countryCodes = [
  { name: "Afghanistan", code: "AF" },
  { name: "Åland Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cote D'Ivoire", code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Korea, Democratic People'S Republic of", code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lao People'S Democratic Republic", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia and Montenegro", code: "CS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.S.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

export const countryStateCity = [
  {
    name: "United States",
    code: "US",
    states: [
      {
        name: "New York",
        code: "NY",
        cities: [
          {
            name: "New York City",
            code: "NYC",
          },
          {
            name: "Buffalo",
            code: "BUF",
          },
        ],
      },
      {
        name: "California",
        code: "CA",
        cities: [
          {
            name: "Los Angeles",
            code: "LA",
          },
          {
            name: "San Francisco",
            code: "SF",
          },
        ],
      },
    ],
  },
  {
    name: "Canada",
    code: "CA",
    states: [
      {
        name: "Ontario",
        code: "ON",
        cities: [
          {
            name: "Toronto",
            code: "TOR",
          },
          {
            name: "Ottawa",
            code: "OTT",
          },
        ],
      },
      {
        name: "Quebec",
        code: "QC",
        cities: [
          {
            name: "Montreal",
            code: "MTL",
          },
          {
            name: "Quebec City",
            code: "QUE",
          },
        ],
      },
    ],
  },
];

export const contactCountryCode = [
  {
    country: "Afghanistan",
    code: "AF",
    dial_code: "+93",
  },
  {
    country: "Albania",
    code: "AL",
    dial_code: "+355",
  },
  {
    country: "Algeria",
    code: "DZ",
    dial_code: "+213",
  },
  {
    country: "Andorra",
    code: "AD",
    dial_code: "+376",
  },
  {
    country: "Angola",
    code: "AO",
    dial_code: "+244",
  },
  {
    country: "Antigua and Barbuda",
    code: "AG",
    dial_code: "+1-268",
  },
  {
    country: "Argentina",
    code: "AR",
    dial_code: "+54",
  },
  {
    country: "Armenia",
    code: "AM",
    dial_code: "+374",
  },
  {
    country: "Australia",
    code: "AU",
    dial_code: "+61",
  },
  {
    country: "Austria",
    code: "AT",
    dial_code: "+43",
  },
  {
    country: "Azerbaijan",
    code: "AZ",
    dial_code: "+994",
  },
  {
    country: "Bahamas",
    code: "BS",
    dial_code: "+1-242",
  },
  {
    country: "Bahrain",
    code: "BH",
    dial_code: "+973",
  },
  {
    country: "Bangladesh",
    code: "BD",
    dial_code: "+880",
  },
  {
    country: "Barbados",
    code: "BB",
    dial_code: "+1-246",
  },
  {
    country: "Belarus",
    code: "BY",
    dial_code: "+375",
  },
  {
    country: "Belgium",
    code: "BE",
    dial_code: "+32",
  },
  {
    country: "Belize",
    code: "BZ",
    dial_code: "+501",
  },
  {
    country: "Benin",
    code: "BJ",
    dial_code: "+229",
  },
  {
    country: "Bhutan",
    code: "BT",
    dial_code: "+975",
  },
  {
    country: "Bolivia",
    code: "BO",
    dial_code: "+591",
  },
  {
    country: "Botswana",
    code: "BW",
    dial_code: "+267",
  },
  {
    country: "Brazil",
    code: "BR",
    dial_code: "+55",
  },
  {
    country: "Brunei",
    code: "BN",
    dial_code: "+673",
  },
  {
    country: "Bulgaria",
    code: "BG",
    dial_code: "+359",
  },
  {
    country: "Burkina Faso",
    code: "BF",
    dial_code: "+226",
  },
  {
    country: "Burundi",
    code: "BI",
    dial_code: "+257",
  },
  {
    country: "Cambodia",
    code: "KH",
    dial_code: "+855",
  },
  {
    country: "Cameroon",
    code: "CM",
    dial_code: "+237",
  },
  {
    country: "Canada",
    code: "CA",
    dial_code: "+1",
  },
  {
    country: "Cape Verde",
    code: "CV",
    dial_code: "+238",
  },
  {
    country: "Central African Republic",
    code: "CF",
    dial_code: "+236",
  },
  {
    country: "Chad",
    code: "TD",
    dial_code: "+235",
  },
  {
    country: "Chile",
    code: "CL",
    dial_code: "+56",
  },
  {
    country: "China",
    code: "CN",
    dial_code: "+86",
  },
  {
    country: "Colombia",
    code: "CO",
    dial_code: "+57",
  },
  {
    country: "Comoros",
    code: "KM",
    dial_code: "+269",
  },
  {
    country: "Congo (Brazzaville)",
    code: "CG",
    dial_code: "+242",
  },
  {
    country: "Congo (Kinshasa)",
    code: "CD",
    dial_code: "+243",
  },
  {
    country: "Costa Rica",
    code: "CR",
    dial_code: "+506",
  },
  {
    country: "Cote d'Ivoire",
    code: "CI",
    dial_code: "+225",
  },
  {
    country: "Croatia",
    code: "HR",
    dial_code: "+385",
  },
  {
    country: "Cuba",
    code: "CU",
    dial_code: "+53",
  },
  {
    country: "Cyprus",
    code: "CY",
    dial_code: "+357",
  },
  {
    country: "Czech Republic",
    code: "CZ",
    dial_code: "+420",
  },
  {
    country: "Denmark",
    code: "DK",
    dial_code: "+45",
  },
  {
    country: "Djibouti",
    code: "DJ",
    dial_code: "+253",
  },
  {
    country: "Dominica",
    code: "DM",
    dial_code: "+1-767",
  },
  {
    country: "Dominican Republic",
    code: "DO",
    dial_code: "+1-809, +1-829, +1-849",
  },
  {
    country: "East Timor",
    code: "TL",
    dial_code: "+670",
  },
  {
    country: "Ecuador",
    code: "EC",
    dial_code: "+593",
  },
  {
    country: "Egypt",
    code: "EG",
    dial_code: "+20",
  },
  {
    country: "El Salvador",
    code: "SV",
    dial_code: "+503",
  },
  {
    country: "Equatorial Guinea",
    code: "GQ",
    dial_code: "+240",
  },
  {
    country: "Eritrea",
    code: "ER",
    dial_code: "+291",
  },
  {
    country: "Estonia",
    code: "EE",
    dial_code: "+372",
  },
  {
    country: "Eswatini",
    code: "SZ",
    dial_code: "+268",
  },
  {
    country: "Ethiopia",
    code: "ET",
    dial_code: "+251",
  },
  {
    country: "Fiji",
    code: "FJ",
    dial_code: "+679",
  },
  {
    country: "Finland",
    code: "FI",
    dial_code: "+358",
  },
  {
    country: "France",
    code: "FR",
    dial_code: "+33",
  },
  {
    country: "Gabon",
    code: "GA",
    dial_code: "+241",
  },
  {
    country: "Gambia",
    code: "GM",
    dial_code: "+220",
  },
  {
    country: "Georgia",
    code: "GE",
    dial_code: "+995",
  },
  {
    country: "Germany",
    code: "DE",
    dial_code: "+49",
  },
  {
    country: "Ghana",
    code: "GH",
    dial_code: "+233",
  },
  {
    country: "Greece",
    code: "GR",
    dial_code: "+30",
  },
  {
    country: "Grenada",
    code: "GD",
    dial_code: "+1-473",
  },
  {
    country: "Guatemala",
    code: "GT",
    dial_code: "+502",
  },
  {
    country: "Guinea",
    code: "GN",
    dial_code: "+224",
  },
  {
    country: "Guinea-Bissau",
    code: "GW",
    dial_code: "+245",
  },
  {
    country: "Guyana",
    code: "GY",
    dial_code: "+592",
  },
  {
    country: "Haiti",
    code: "HT",
    dial_code: "+509",
  },
  {
    country: "Honduras",
    code: "HN",
    dial_code: "+504",
  },
  {
    country: "Hungary",
    code: "HU",
    dial_code: "+36",
  },
  {
    country: "Iceland",
    code: "IS",
    dial_code: "+354",
  },
  {
    country: "India",
    code: "IN",
    dial_code: "+91",
  },
  {
    country: "Indonesia",
    code: "ID",
    dial_code: "+62",
  },
  {
    country: "Iran",
    code: "IR",
    dial_code: "+98",
  },
  {
    country: "Iraq",
    code: "IQ",
    dial_code: "+964",
  },
  {
    country: "Ireland",
    code: "IE",
    dial_code: "+353",
  },
  {
    country: "Israel",
    code: "IL",
    dial_code: "+972",
  },
  {
    country: "Italy",
    code: "IT",
    dial_code: "+39",
  },
  {
    country: "Jamaica",
    code: "JM",
    dial_code: "+1-876",
  },
  {
    country: "Japan",
    code: "JP",
    dial_code: "+81",
  },
  {
    country: "Jordan",
    code: "JO",
    dial_code: "+962",
  },
  {
    country: "Kazakhstan",
    code: "KZ",
    dial_code: "+7",
  },
  {
    country: "Kenya",
    code: "KE",
    dial_code: "+254",
  },
  {
    country: "Kiribati",
    code: "KI",
    dial_code: "+686",
  },
  {
    country: "Korea, North",
    code: "KP",
    dial_code: "+850",
  },
  {
    country: "Korea, South",
    code: "KR",
    dial_code: "+82",
  },
  {
    country: "Kuwait",
    code: "KW",
    dial_code: "+965",
  },
  {
    country: "Kyrgyzstan",
    code: "KG",
    dial_code: "+996",
  },
  {
    country: "Laos",
    code: "LA",
    dial_code: "+856",
  },
  {
    country: "Latvia",
    code: "LV",
    dial_code: "+371",
  },
  {
    country: "Lebanon",
    code: "LB",
    dial_code: "+961",
  },
  {
    country: "Lesotho",
    code: "LS",
    dial_code: "+266",
  },

  {
    country: "Madagascar",
    code: "MG",
    dial_code: "+261",
  },
  {
    country: "Malawi",
    code: "MW",
    dial_code: "+265",
  },
  {
    country: "Malaysia",
    code: "MY",
    dial_code: "+60",
  },
  {
    country: "Maldives",
    code: "MV",
    dial_code: "+960",
  },
  {
    country: "Mali",
    code: "ML",
    dial_code: "+223",
  },
  {
    country: "Malta",
    code: "MT",
    dial_code: "+356",
  },
  {
    country: "Marshall Islands",
    code: "MH",
    dial_code: "+692",
  },
  {
    country: "Mauritania",
    code: "MR",
    dial_code: "+222",
  },
  {
    country: "Mauritius",
    code: "MU",
    dial_code: "+230",
  },
  {
    country: "Mexico",
    code: "MX",
    dial_code: "+52",
  },
  {
    country: "Micronesia",
    code: "FM",
    dial_code: "+691",
  },
  {
    country: "Moldova",
    code: "MD",
    dial_code: "+373",
  },
  {
    country: "Monaco",
    code: "MC",
    dial_code: "+377",
  },
  {
    country: "Mongolia",
    code: "MN",
    dial_code: "+976",
  },
  {
    country: "Montenegro",
    code: "ME",
    dial_code: "+382",
  },
  {
    country: "Morocco",
    code: "MA",
    dial_code: "+212",
  },
  {
    country: "Mozambique",
    code: "MZ",
    dial_code: "+258",
  },
  {
    country: "Myanmar",
    code: "MM",
    dial_code: "+95",
  },
  {
    country: "Namibia",
    code: "NA",
    dial_code: "+264",
  },
  {
    country: "Nauru",
    code: "NR",
    dial_code: "+674",
  },
  {
    country: "Nepal",
    code: "NP",
    dial_code: "+977",
  },
  {
    country: "Netherlands",
    code: "NL",
    dial_code: "+31",
  },
  {
    country: "New Zealand",
    code: "NZ",
    dial_code: "+64",
  },
  {
    country: "Nicaragua",
    code: "NI",
    dial_code: "+505",
  },
  {
    country: "Niger",
    code: "NE",
    dial_code: "+227",
  },
  {
    country: "Nigeria",
    code: "NG",
    dial_code: "+234",
  },
  {
    country: "North Macedonia",
    code: "MK",
    dial_code: "+389",
  },
  {
    country: "Norway",
    code: "NO",
    dial_code: "+47",
  },
  {
    country: "Oman",
    code: "OM",
    dial_code: "+968",
  },
  {
    country: "Pakistan",
    code: "PK",
    dial_code: "+92",
  },
  {
    country: "Palau",
    code: "PW",
    dial_code: "+680",
  },
  {
    country: "Panama",
    code: "PA",
    dial_code: "+507",
  },
  {
    country: "Papua New Guinea",
    code: "PG",
    dial_code: "+675",
  },
  {
    country: "Paraguay",
    code: "PY",
    dial_code: "+595",
  },
  {
    country: "Peru",
    code: "PE",
    dial_code: "+51",
  },
  {
    country: "Philippines",
    code: "PH",
    dial_code: "+63",
  },
  {
    country: "Poland",
    code: "PL",
    dial_code: "+48",
  },
  {
    country: "Portugal",
    code: "PT",
    dial_code: "+351",
  },
  {
    country: "Qatar",
    code: "QA",
    dial_code: "+974",
  },
  {
    country: "Romania",
    code: "RO",
    dial_code: "+40",
  },
  {
    country: "Russia",
    code: "RU",
    dial_code: "+7",
  },
  {
    country: "Rwanda",
    code: "RW",
    dial_code: "+250",
  },
  {
    country: "Saint Kitts and Nevis",
    code: "KN",
    dial_code: "+1-869",
  },
  {
    country: "Saint Lucia",
    code: "LC",
    dial_code: "+1-758",
  },
  {
    country: "Saint Vincent and the Grenadines",
    code: "VC",
    dial_code: "+1-784",
  },
  {
    country: "Samoa",
    code: "WS",
    dial_code: "+685",
  },
  {
    country: "San Marino",
    code: "SM",
    dial_code: "+378",
  },
  {
    country: "Sao Tome and Principe",
    code: "ST",
    dial_code: "+239",
  },
  {
    country: "Saudi Arabia",
    code: "SA",
    dial_code: "+966",
  },
  {
    country: "Senegal",
    code: "SN",
    dial_code: "+221",
  },
  {
    country: "Serbia",
    code: "RS",
    dial_code: "+381",
  },
  {
    country: "Seychelles",
    code: "SC",
    dial_code: "+248",
  },
  {
    country: "Sierra Leone",
    code: "SL",
    dial_code: "+232",
  },
  {
    country: "Singapore",
    code: "SG",
    dial_code: "+65",
  },
  {
    country: "Slovakia",
    code: "SK",
    dial_code: "+421",
  },
  {
    country: "Slovenia",
    code: "SI",
    dial_code: "+386",
  },
  {
    country: "Solomon Islands",
    code: "SB",
    dial_code: "+677",
  },
  {
    country: "Somalia",
    code: "SO",
    dial_code: "+252",
  },
  {
    country: "South Africa",
    code: "ZA",
    dial_code: "+27",
  },
  {
    country: "South Korea",
    code: "KR",
    dial_code: "+82",
  },
  {
    country: "South Sudan",
    code: "SS",
    dial_code: "+211",
  },
  {
    country: "Spain",
    code: "ES",
    dial_code: "+34",
  },
  {
    country: "Sri Lanka",
    code: "LK",
    dial_code: "+94",
  },
  {
    country: "Sudan",
    code: "SD",
    dial_code: "+249",
  },
  {
    country: "Suriname",
    code: "SR",
    dial_code: "+597",
  },
  {
    country: "Swaziland",
    code: "SZ",
    dial_code: "+268",
  },
  {
    country: "Sweden",
    code: "SE",
    dial_code: "+46",
  },
  {
    country: "Switzerland",
    code: "CH",
    dial_code: "+41",
  },
  {
    country: "Syria",
    code: "SY",
    dial_code: "+963",
  },
  {
    country: "Taiwan",
    code: "TW",
    dial_code: "+886",
  },
  {
    country: "Tajikistan",
    code: "TJ",
    dial_code: "+992",
  },
  {
    country: "Tanzania",
    code: "TZ",
    dial_code: "+255",
  },
  {
    country: "Thailand",
    code: "TH",
    dial_code: "+66",
  },
  {
    country: "Timor-Leste",
    code: "TL",
    dial_code: "+670",
  },
  {
    country: "Togo",
    code: "TG",
    dial_code: "+228",
  },
  {
    country: "Tonga",
    code: "TO",
    dial_code: "+676",
  },
  {
    country: "Trinidad and Tobago",
    code: "TT",
    dial_code: "+1-868",
  },
  {
    country: "Tunisia",
    code: "TN",
    dial_code: "+216",
  },
  {
    country: "Turkey",
    code: "TR",
    dial_code: "+90",
  },
  {
    country: "Turkmenistan",
    code: "TM",
    dial_code: "+993",
  },
  {
    country: "Tuvalu",
    code: "TV",
    dial_code: "+688",
  },
  {
    country: "Uganda",
    code: "UG",
    dial_code: "+256",
  },
  {
    country: "Ukraine",
    code: "UA",
    dial_code: "+380",
  },
  {
    country: "United Arab Emirates",
    code: "AE",
    dial_code: "+971",
  },
  {
    country: "United Kingdom",
    code: "GB",
    dial_code: "+44",
  },
  {
    country: "United States",
    code: "US",
    dial_code: "+1",
  },
  {
    country: "Uruguay",
    code: "UY",
    dial_code: "+598",
  },
  {
    country: "Uzbekistan",
    code: "UZ",
    dial_code: "+998",
  },
  {
    country: "Vanuatu",
    code: "VU",
    dial_code: "+678",
  },
  {
    country: "Vatican City",
    code: "VA",
    dial_code: "+39-06",
  },
  {
    country: "Venezuela",
    code: "VE",
    dial_code: "+58",
  },
  {
    country: "Vietnam",
    code: "VN",
    dial_code: "+84",
  },
  {
    country: "Yemen",
    code: "YE",
    dial_code: "+967",
  },
  {
    country: "Zambia",
    code: "ZM",
    dial_code: "+260",
  },
  {
    country: "Zimbabwe",
    code: "ZW",
    dial_code: "+263",
  },
];

export const languages = [
  { code: "aa", name: "Afar" },
  { code: "ab", name: "Abkhazian" },
  { code: "ae", name: "Avestan" },
  { code: "af", name: "Afrikaans" },
  { code: "ak", name: "Akan" },
  { code: "am", name: "Amharic" },
  { code: "an", name: "Aragonese" },
  { code: "ar", name: "Arabic" },
  { code: "as", name: "Assamese" },
  { code: "av", name: "Avaric" },
  { code: "ay", name: "Aymara" },
  { code: "az", name: "Azerbaijani" },
  { code: "ba", name: "Bashkir" },
  { code: "be", name: "Belarusian" },
  { code: "bg", name: "Bulgarian" },
  { code: "bh", name: "Bihari languages" },
  { code: "bi", name: "Bislama" },
  { code: "bm", name: "Bambara" },
  { code: "bn", name: "Bengali" },
  { code: "bo", name: "Tibetan" },
  { code: "br", name: "Breton" },
  { code: "bs", name: "Bosnian" },
  { code: "ca", name: "Catalan; Valencian" },
  { code: "ce", name: "Chechen" },
  { code: "ch", name: "Chamorro" },
  { code: "co", name: "Corsican" },
  { code: "cr", name: "Cree" },
  { code: "cs", name: "Czech" },
  {
    code: "cu",
    name: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
  },
  { code: "cv", name: "Chuvash" },
  { code: "cy", name: "Welsh" },
  { code: "da", name: "Danish" },
  { code: "de", name: "German" },
  { code: "dv", name: "Divehi; Dhivehi; Maldivian" },
  { code: "dz", name: "Dzongkha" },
  { code: "ee", name: "Ewe" },
  { code: "el", name: "Greek, Modern (1453-)" },
  { code: "en", name: "English" },
  { code: "eo", name: "Esperanto" },
  { code: "es", name: "Spanish; Castilian" },
  { code: "et", name: "Estonian" },
  { code: "eu", name: "Basque" },
  { code: "fa", name: "Persian" },
  { code: "ff", name: "Fulah" },
  { code: "fi", name: "Finnish" },
  { code: "fj", name: "Fijian" },
  { code: "fo", name: "Faroese" },
  { code: "fr", name: "French" },
  { code: "fy", name: "Western Frisian" },
  { code: "ga", name: "Irish" },
  { code: "gd", name: "Gaelic; Scomttish Gaelic" },
  { code: "gl", name: "Galician" },
  { code: "gn", name: "Guarani" },
  { code: "gu", name: "Gujarati" },
  { code: "gv", name: "Manx" },
  { code: "ha", name: "Hausa" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "ho", name: "Hiri Motu" },
  { code: "hr", name: "Croatian" },
  { code: "ht", name: "Haitian; Haitian Creole" },
  { code: "hu", name: "Hungarian" },
  { code: "hy", name: "Armenian" },
  { code: "hz", name: "Herero" },
  {
    code: "ia",
    name: "Interlingua (International Auxiliary Language Association)",
  },
  { code: "id", name: "Indonesian" },
  { code: "ie", name: "Interlingue; Occidental" },
  { code: "ig", name: "Igbo" },
  { code: "ii", name: "Sichuan Yi; Nuosu" },
  { code: "ik", name: "Inupiaq" },
  { code: "io", name: "Ido" },
  { code: "is", name: "Icelandic" },
  { code: "it", name: "Italian" },
  { code: "iu", name: "Inuktitut" },
  { code: "ja", name: "Japanese" },
  { code: "jv", name: "Javanese" },
  { code: "ka", name: "Georgian" },
  { code: "kg", name: "Kongo" },
  { code: "ki", name: "Kikuyu; Gikuyu" },
  { code: "kj", name: "Kuanyama; Kwanyama" },
  { code: "kk", name: "Kazakh" },
  { code: "kl", name: "Kalaallisut; Greenlandic" },
  { code: "km", name: "Central Khmer" },
  { code: "kn", name: "Kannada" },
  { code: "ko", name: "Korean" },
  { code: "kr", name: "Kanuri" },
  { code: "ks", name: "Kashmiri" },
  { code: "ku", name: "Kurdish" },
  { code: "kv", name: "Komi" },
  { code: "kw", name: "Cornish" },
  { code: "ky", name: "Kirghiz; Kyrgyz" },
  { code: "la", name: "Latin" },
  { code: "lb", name: "Luxembourgish; Letzeburgesch" },
  { code: "lg", name: "Ganda" },
  { code: "li", name: "Limburgan; Limburger; Limburgish" },
  { code: "ln", name: "Lingala" },
  { code: "lo", name: "Lao" },
  { code: "lt", name: "Lithuanian" },
  { code: "lu", name: "Luba-Katanga" },
  { code: "lv", name: "Latvian" },
  { code: "mg", name: "Malagasy" },
  { code: "mh", name: "Marshallese" },
  { code: "mi", name: "Maori" },
  { code: "mk", name: "Macedonian" },
  { code: "ml", name: "Malayalam" },
  { code: "mn", name: "Mongolian" },
  { code: "mr", name: "Marathi" },
  { code: "ms", name: "Malay" },
  { code: "mt", name: "Maltese" },
  { code: "my", name: "Burmese" },
  { code: "na", name: "Nauru" },
  {
    code: "nb",
    name: "Bokmål, Norwegian; Norwegian Bokmål",
  },
  { code: "nd", name: "Ndebele, North; North Ndebele" },
  { code: "ne", name: "Nepali" },
  { code: "ng", name: "Ndonga" },
  { code: "nl", name: "Dutch; Flemish" },
  { code: "nn", name: "Norwegian Nynorsk; Nynorsk, Norwegian" },
  { code: "no", name: "Norwegian" },
  { code: "nr", name: "Ndebele, South; South Ndebele" },
  { code: "nv", name: "Navajo; Navaho" },
  { code: "ny", name: "Chichewa; Chewa; Nyanja" },
  { code: "oc", name: "Occitan (post 1500)" },
  { code: "oj", name: "Ojibwa" },
  { code: "om", name: "Oromo" },
  { code: "or", name: "Oriya" },
  { code: "os", name: "Ossetian; Ossetic" },
  { code: "pa", name: "Panjabi; Punjabi" },
  { code: "pi", name: "Pali" },
  { code: "pl", name: "Polish" },
  { code: "ps", name: "Pushto; Pashto" },
  { code: "pt", name: "Portuguese" },
  { code: "qu", name: "Quechua" },
  { code: "rm", name: "Romansh" },
  { code: "rn", name: "Rundi" },
  { code: "ro", name: "Romanian; Moldavian; Moldovan" },
  { code: "ru", name: "Russian" },
  { code: "rw", name: "Kinyarwanda" },
  { code: "sa", name: "Sanskrit" },
  { code: "sc", name: "Sardinian" },
  { code: "sd", name: "Sindhi" },
  { code: "se", name: "Northern Sami" },
  { code: "sg", name: "Sango" },
  { code: "si", name: "Sinhala; Sinhalese" },
  { code: "sk", name: "Slovak" },
  { code: "sl", name: "Slovenian" },
  { code: "sm", name: "Samoan" },
  { code: "sn", name: "Shona" },
  { code: "so", name: "Somali" },
  { code: "sq", name: "Albanian" },
  { code: "sr", name: "Serbian" },
  { code: "ss", name: "Swati" },
  { code: "st", name: "Sotho, Southern" },
  { code: "su", name: "Sundanese" },
  { code: "sv", name: "Swedish" },
  { code: "sw", name: "Swahili" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "tg", name: "Tajik" },
  { code: "th", name: "Thai" },
  { code: "ti", name: "Tigrinya" },
  { code: "tk", name: "Turkmen" },
  { code: "tl", name: "Tagalog" },
  { code: "tn", name: "Tswana" },
  { code: "to", name: "Tonga (Tonga Islands)" },
  { code: "tr", name: "Turkish" },
  { code: "ts", name: "Tsonga" },
  { code: "tt", name: "Tatar" },
  { code: "tw", name: "Twi" },
  { code: "ty", name: "Tahitian" },
  { code: "ug", name: "Uighur; Uyghur" },
  { code: "uk", name: "Ukrainian" },
  { code: "ur", name: "Urdu" },
  { code: "uz", name: "Uzbek" },
  { code: "ve", name: "Venda" },
  { code: "vi", name: "Vietnamese" },
  { code: "vo", name: "Volapük" },
  { code: "wa", name: "Walloon" },
  { code: "wo", name: "Wolof" },
  { code: "xh", name: "Xhosa" },
  { code: "yi", name: "Yiddish" },
  { code: "yo", name: "Yoruba" },
  { code: "za", name: "Zhuang; Chuang" },
  { code: "zh", name: "Chinese" },
  { code: "zu", name: "Zulu" },
];
